"""Parse Nmap XML output into PortHawk ScanResult objects.

Handles the full nmaprun XML format (nmap -oX). No external dependencies —
xml.etree.ElementTree from stdlib is enough for this.

Nmap state → PortState mapping:
  open           → OPEN
  closed         → CLOSED
  filtered       → FILTERED
  open|filtered  → FILTERED  (can't tell, treat pessimistically)
  closed|filtered → FILTERED

Port records without a state element are skipped — broken XML isn't our problem.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path

from porthawk.scanner import PortState, ScanResult

# nmap uses "/" in some compound state strings; take the first word
_STATE_MAP: dict[str, PortState] = {
    "open": PortState.OPEN,
    "closed": PortState.CLOSED,
    "filtered": PortState.FILTERED,
    "unfiltered": PortState.OPEN,  # ACK scan — port reachable
    "open|filtered": PortState.FILTERED,
    "closed|filtered": PortState.FILTERED,
}


def _parse_state(state_str: str) -> PortState:
    return _STATE_MAP.get(state_str.lower(), PortState.FILTERED)


def _parse_host(host_elem: ET.Element) -> list[ScanResult]:
    """Extract ScanResults from a single <host> element."""
    # skip hosts that were down during the scan
    status = host_elem.find("status")
    if status is not None and status.get("state") == "down":
        return []

    # prefer IPv4, fall back to IPv6, then hostname
    addr = ""
    for address in host_elem.findall("address"):
        addrtype = address.get("addrtype", "")
        if addrtype == "ipv4":
            addr = address.get("addr", "")
            break
        if addrtype == "ipv6" and not addr:
            addr = address.get("addr", "")

    if not addr:
        # try the first hostname as a last resort
        hn = host_elem.find("hostnames/hostname")
        addr = hn.get("name", "") if hn is not None else ""

    if not addr:
        return []

    results: list[ScanResult] = []
    ports_elem = host_elem.find("ports")
    if ports_elem is None:
        return []

    for port_elem in ports_elem.findall("port"):
        protocol = port_elem.get("protocol", "tcp")
        if protocol not in ("tcp", "udp"):
            continue

        portid_str = port_elem.get("portid", "")
        try:
            port_num = int(portid_str)
        except ValueError:
            continue

        state_elem = port_elem.find("state")
        if state_elem is None:
            continue
        state = _parse_state(state_elem.get("state", "filtered"))

        # service info — optional in minimal nmap runs
        service_name: str | None = None
        service_version: str | None = None
        banner: str | None = None

        svc = port_elem.find("service")
        if svc is not None:
            service_name = svc.get("name") or None
            product = svc.get("product", "")
            version = svc.get("version", "")
            extrainfo = svc.get("extrainfo", "")

            # build a version string from what nmap found
            parts = [p for p in (product, version) if p]
            if parts:
                service_version = " ".join(parts)

            # banner = everything nmap knows about the service
            banner_parts = [p for p in (product, version, extrainfo) if p]
            banner = " ".join(banner_parts) or None

        results.append(
            ScanResult(
                host=addr,
                port=port_num,
                protocol=protocol,
                state=state,
                service_name=service_name,
                service_version=service_version,
                banner=banner,
            )
        )

    return results


def parse_nmap_xml(source: str | Path) -> list[ScanResult]:
    """Parse an Nmap XML file and return a flat list of ScanResults.

    Args:
        source: Path to an .xml file generated by nmap -oX.

    Returns:
        List of ScanResult, one per port per host. Multiple hosts in one
        nmap run are all included.

    Raises:
        FileNotFoundError: if the file doesn't exist.
        ValueError: if the XML isn't a valid nmaprun document.
    """
    path = Path(source)
    if not path.exists():
        raise FileNotFoundError(f"Nmap XML not found: {path}")

    try:
        tree = ET.parse(path)
    except ET.ParseError as exc:
        raise ValueError(f"Invalid XML in {path}: {exc}") from exc

    root = tree.getroot()
    if root.tag != "nmaprun":
        raise ValueError(
            f"Expected <nmaprun> root element, got <{root.tag}>. "
            "Is this actually an nmap -oX output file?"
        )

    results: list[ScanResult] = []
    for host_elem in root.findall("host"):
        results.extend(_parse_host(host_elem))

    return results
